const CANDIDATES = {
  vsuru: [
    { id: '1', name: '김승규' },
    { id: '2', name: '윤종규' },
    { id: '3', name: '김진수' },
    { id: '4', name: '김민재' },
    { id: '5', name: '정우영' },
    { id: '6', name: '황인범' },
    { id: '7', name: '손흥민' },
    { id: '8', name: '백승호' },
    { id: '9', name: '조규성' },
    { id: '10', name: '이재성' },
    { id: '11', name: '황희찬' },
    { id: '12', name: '송범근' },
    { id: '13', name: '손준호' },
    { id: '14', name: '홍철' },
    { id: '15', name: '김문환' },
    { id: '16', name: '황의조' },
    { id: '17', name: '나상호' },
    { id: '18', name: '이강인' },
    { id: '19', name: '김영권' },
    { id: '20', name: '권경원' },
    { id: '21', name: '조현우' },
    { id: '22', name: '권창훈' },
    { id: '23', name: '김태환' },
    { id: '24', name: '조유민' },
    { id: '25', name: '정우영' },
    { id: '26', name: '송민규' },
  ],
  worldcup: [
    { id: '1', name: '가나' },
    { id: '2', name: '네덜란드' },
    { id: '3', name: '대한민국' },
    { id: '4', name: '덴마크' },
    { id: '5', name: '독일' },
    { id: '6', name: '멕시코' },
    { id: '7', name: '모로코' },
    { id: '8', name: '미국' },
    { id: '9', name: '벨기에' },
    { id: '10', name: '브라질' },
    { id: '11', name: '사우디아라비아' },
    { id: '12', name: '세네갈' },
    { id: '13', name: '세르비아' },
    { id: '14', name: '스위스' },
    { id: '15', name: '스페인' },
    { id: '16', name: '아르헨티나' },
    { id: '17', name: '에콰도르' },
    { id: '18', name: '우루과이' },
    { id: '19', name: '웨일스' },
    { id: '20', name: '이란' },
    { id: '21', name: '일본' },
    { id: '22', name: '잉글랜드' },
    { id: '23', name: '카메룬' },
    { id: '24', name: '카타르' },
    { id: '25', name: '캐나다' },
    { id: '26', name: '코스타리카' },
    { id: '27', name: '크로아티아' },
    { id: '28', name: '튀니지' },
    { id: '29', name: '포르투갈' },
    { id: '30', name: '폴란드' },
    { id: '31', name: '프랑스' },
    { id: '32', name: '호주' },
  ],
  movie: [
    { id: '1', name: '하자' },
    { id: '2', name: '접자' },
  ],
  hobby: [
    { id: '1', name: '하자' },
    { id: '2', name: '접자' },
  ],
};

export default CANDIDATES;
